#+title: Model curation process

A python module for the model curation process in the HBP. 

It curates entries from their submission in the Model Catalog by the HBP contributors to their publications in the HBP Knowledge Graph. The curation process includes automatic processes of database updates together with manual editing of entries in Google Spreadsheets and email interactions with the model contributors.

** Curation schematic (current pipeline)

[[docs/process.svg]]

** Model template

#+BEGIN_SRC python
{
    'name':'', # a string
    
    'alias':'', # a string
    
    'author':[], # a set of uuid

    'description':'', # a string

    'identifier':'', # an uuid

    'private':'', # a string either "TRUE" or "FALSE"

    # a set of Knowledge Graph metadata
    # stored here as a string corresponding to their uuid in the Knowledge Graph
    'associated_dataset':[],
    'associated_method':[],
    'associated_experimental_preparation':[],
    'associated_software':[],
    
    'version':[
	{'source':'',
	 'name':''},
	{'source':'',
	 'name':''},
    ],
    
    'images':[
	{'url':'',
	 'caption':''}
    ],
}    
#+END_SRC

** Use of scripts


run the =setting_env_variables.sh=  script in the shell 

#+BEGIN_SRC bash
cd folder_where_you_have_cloned_the_repo/model-curation/
source setting_env_variables.sh
#+END_SRC 

** Dependencies

Two python modules of the Human Brain Project ecosystem:

- [[https://github.com/HumanBrainProject/fairgraph][fairgraph]]: A high-level Python API for the HBP Knowledge Graph
- [[https://github.com/HumanBrainProject/hbp-validation-client][hbp-validation-client]]: A Python package for working with the Human Brain Project Model Validation Framework.

The Python API for working with Google Spreadsheets:

- [[https://developers.google.com/sheets/api][Google Spreadsheet API]]

Follow the instructions to get the credentials at:

https://developers.google.com/sheets/api/quickstart/python

** Configuration file

A file 
#+BEGIN_SRC python
import os

# location of your json files for the HBP logins, as a python path
hbp_token_file=os.path.join(os.path.expanduser('~'), 'Downloads', 'HBP.json')
hbp_storage_token_file=os.path.join(os.path.expanduser('~'), 'Downloads', 'config.json')

# Google spreadsheet credential logins
...

# ID of Google Spreadsheets 
SGA2_SP6_SPREADSHEET_ID= '...' 
SGA2_SP3_SPREADSHEET_ID='...'


#+END_SRC python

** Stats

A detailed analysis of the curation pipeline is available at:

https://github.com/yzerlaut/model-curation/blob/master/stats/summary.org

