#+title: Model curation process

A python module for the model curation process in the HBP. 

It curates entries from their submission in the Model Catalog by the HBP contributors to their publications in the HBP Knowledge Graph. The curation process includes automatic processes of database updates together with manual editing of entries in Google Spreadsheets and email interactions with the model contributors.

** Curation schematic (current pipeline)

[[docs/process.svg]]

** Model template

The metadata are stored as strings. Either "free" strings or strings corresponding to the UUID in the Knowledge Graph (e.g. the metadata related to the Person Yann Zerlaut has the UUID: =003beed8-1ee8-45ec-8737-785ca6239ef0=).

An empty template is stored in the =model_template.py= file. It reads:
#+BEGIN_SRC python
template = {
    
    "name":"", # a string
    
    "alias":"", # a string
    
    "author":[], # a set of a KG UUIDs

    "description":"", # a string

    "identifier":"", # a KG UUID -> generated during model curation !

    "private":"", # a string either "TRUE" or "FALSE"

    # ------ KG METADATA -------- # 
    "abstraction_level":"", # a KG UUID
    "brain_region":"", # a KG UUID
    "cell_type":["", ""], # a set of KG UUIDs
    "code_format":"", # a string
    "creation_date":"", # a KG UUID
    "license":"", # a KG UUID
    "model_scope":"", # a KG UUID
    "model_type":"", # a KG UUID
    "organization":"", # a KG UUID
    "owner":"", # a KG UUID
    "pla_components":"", # a KG UUID
    "project":"", # a KG UUID
    "associated_dataset":[], # a KG UUID
    "associated_method":[], # a KG UUID
    "associated_experimental_preparation":[], # a set of KG UUIDs
    "used_software":[],
    
    # ------ VERSIONS -------- # 
    "version":[
	{"source":"",
	 "name":""},
	{"source":"",
	 "name":""},
    ],
    
    # ------ VERSIONS -------- # 
    "images":[
	{"url":"",
	 "caption":""}
    ],
}    
#+END_SRC

** Use of scripts


run the =setting_env_variables.sh=  script in the shell 

#+BEGIN_SRC bash
cd folder_where_you_have_cloned_the_repo/model-curation/
source setting_env_variables.sh
#+END_SRC 

** Dependencies

Two python modules of the Human Brain Project ecosystem:

- [[https://github.com/HumanBrainProject/fairgraph][fairgraph]]: A high-level Python API for the HBP Knowledge Graph
- [[https://github.com/HumanBrainProject/hbp-validation-client][hbp-validation-client]]: A Python package for working with the Human Brain Project Model Validation Framework.

The Python API for working with Google Spreadsheets:

- [[https://developers.google.com/sheets/api][Google Spreadsheet API]]

Follow the instructions to get the credentials at:

https://developers.google.com/sheets/api/quickstart/python

** Configuration file

A file 
#+BEGIN_SRC python
import os

# location of your json files for the HBP logins, as a python path
hbp_token_file=os.path.join(os.path.expanduser('~'), 'Downloads', 'HBP.json')
hbp_storage_token_file=os.path.join(os.path.expanduser('~'), 'Downloads', 'config.json')

# Google spreadsheet credential logins
...

# ID of Google Spreadsheets 
SGA2_SP6_SPREADSHEET_ID= '...' 
SGA2_SP3_SPREADSHEET_ID='...'


#+END_SRC python

** Stats

A detailed analysis of the curation pipeline is available at:

https://github.com/yzerlaut/model-curation/blob/master/stats/summary.org

